# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - uzamkavets-testvisualstudioreactapp

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
env:
  REACT_APP_TEST_VAR: rrr
  REACT_APP_SITE_KEY: 6Ld_0IAmAAAAAMlcdFrZj3mOvvvQRqsawccJwCee

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
          
      # Zip
      - name: Zip Release
        # You may pin to the exact commit or the version.
        # uses: TheDoctor0/zip-release@a24011d8d445e4da5935a7e73c1f98e22a439464
        uses: TheDoctor0/zip-release@0.7.1
        with:
          # Filename for archive
          filename: release.zip
          # Base path for archive files
          path: ./build/*
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'uzamkavets-testvisualstudioreactapp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_18418C333FDA4771A404FB0BFE036C1F }}
          package: release.zip
